### ISSUE TITLE
Add some reference to the dockerhub image

### ISSUE THREAD

**Issue by gleichda** [steinbrueckri/debug#54]
https://hub.docker.com/r/steinbrueckri/debug This looks so empty and sad...

**Comment by steinbrueckri** [comment]
@gleichda Have you an idea💡?

**Comment by gleichda** [comment]
Just place the readme there and link the GH repo?

**Comment by steinbrueckri** [comment]
![image](https://user-images.githubusercontent.com/578303/116064436-4cd83b80-a686-11eb-99fe-c28258101175.png)

**Comment by steinbrueckri** [comment]
Just for the record, that's just a copy and paste. Maybe this needs an update in the future ...
